apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdumper-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdumper-ui
  template:
    metadata:
      labels:
        app: gdumper-ui
    spec:
      containers:
        - name: gdumper-ui
          image: gdumper-ui:1.0.14
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf  # Nginx 默认配置路径
              subPath: default.conf          # 只挂载 default.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: gdumper-ui-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: gdumper-ui

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        access_log  /var/log/nginx/host.access.log  main;
        error_log /var/log/nginx/localhost.error.log error;

        location /api/v1 {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://gdumper-service:8808;
        }

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;

            try_files $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }